version: "2"
services:
  wordpress:
    build: ./docker/wordpress
    env_file:
      - .env
    links:
      - mysql:mysql
    volumes:
      - ./src/wordpress/themes:/var/www/html/wp-content/themes
      - ./src/wordpress/plugins:/var/www/html/wp-content/plugins
      - ./src/wordpress/uploads:/var/www/html/wp-content/uploads
  nginx:
    build: ./docker/nginx
    ports:
      - 80:80
    links:
     - wordpress
    volumes_from:
     - wordpress
  mysql:
    build: ./docker/mysql
    env_file:
      - .env
    ports:
      - 3306:3306
  npm:
    build: ./docker/node
    env_file:
      - .env
    links:
      - nginx:dev.com
    ports:
      - 3000:3000
      - 3001:3001
    volumes_from:
      - wordpress
    volumes:
      - ./src/styles:/app
